### ISSUE TITLE
Creating the text input file for gdalbuiltvrt when changing the tile of interest

### ISSUE THREAD

**Issue by egagli** [scottyhq/sentinel1-rtc#1]
When changing the tile of interest uncomment the gdalbuildvrt command and add the following block before: (this will create the required text file for the new area to be used in the gdalbuildvrt command)
```
with open('s3paths.txt', 'w') as f:
    for key in keys:
        f.write("/vsis3/%s\n" % key)
```

**Comment by scottyhq** [comment]
thanks @egagli ! i'd definitely like to make this workflow easy for any MGRS grid square, any chance you can submit this change as a PR?

**Comment by egagli** [comment]
> thanks @egagli ! i'd definitely like to make this workflow easy for any MGRS grid square, any chance you can submit this change as a PR? 

Yes, i'll do that!
